---
openshift_cluster_content:
  - galaxy_requirements: "{{ inventory_dir }}/../requirements.yaml"
  - object: Openshift Image Registry Configuration
    pre_steps: 
    - role: self/roles/discover
    content: 
    - name: Image Registry Route
      file: "{{ inventory_dir }}/../templates/image-registry-route.j2"
      tags: 
      - image_registry
